name = "Geverscraft 2026"
author = "Rob Gevers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68b965dc9c56e3ba0652a0ccbab2a39311b144d3b738c075d743f75d1165de64"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.32-beta"
