name = "Geverscraft 2026"
author = "Rob Gevers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7865e9ce14924a4774967d7ef7f2559cb7b86c7d6a4bf7ff9ae02dc0af54a275"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.32-beta"
